[build]
  command = "npm run build"  
  publish = "dist"       

[build.environment]
  NODE_VERSION = "14" 

[[redirects]]
  from = "/*" 
  to = "/layout.ejs" 
  status = 200 

[[headers]]
  for = "/*" 
    [headers.values]
    Access-Control-Allow-Origin = "*"  


